<pre class='metadata'>
Title: The verifyTLSServerCertificate API
Shortname: verifyTLSServerCertificate for IWA
Level: None
Status: w3c/UD
Repository: explainers-by-googlers/verifyTLSServerCertificateForIWA
URL: https://explainers-by-googlers.github.io/verifyTLSServerCertificateForIWA
Editor: Uladzislau Krot, Google https://google.com, vkrot@google.com
Abstract: This is Isolated Web App api that allows applications that communicate over TCP/UDP to verify server certificates.
Markup Shorthands: markdown yes, css no
Complain About: accidental-2119 yes, missing-example-ids yes
Assume Explicit For: yes
Die On: warning
WPT Path Prefix: TODO-API-LABEL
WPT Display: closed
Include MDN Panels: if possible
Include Can I Use Panels: yes
</pre>

Introduction {#intro}
=====================

For now, see the [explainer](https://explainers-by-googlers.github.io/verifyTLSServerCertificateForIWA).

See [https://garykac.github.io/procspec/](https://garykac.github.io/procspec/),
[https://dlaliberte.github.io/bikeshed-intro/index.html](https://dlaliberte.github.io/bikeshed-intro/index.html),
and [https://speced.github.io/bikeshed/](https://speced.github.io/bikeshed/) to get started on your
specification.
